// Local Host
###
GET https://localhost:8080/contacts

###

GET https://localhost:8080/contacts/63ba681b98d9e07211d23277


###

GET https://localhost:8080/contacts/63ba681b98d9e07211d23278

###

GET https://localhost:8080/contacts/63ba681b98d9e07211d23279

// Production

###

GET https://cse341-lesson2-l4cx.onrender.com/contacts

###

GET https://cse341-lesson2-l4cx.onrender.com/contacts/63ba681b98d9e07211d23277


###

GET https://cse341-lesson2-l4cx.onrender.com/contacts/63ba681b98d9e07211d23278


###

GET https://cse341-lesson2-l4cx.onrender.com/contacts/63ba681b98d9e07211d23279



###



//Lesson 3 Start.....................................................................................


###
GET https://localhost:8080/contacts  https/1.1

###
POST https://localhost:8080/contacts https/1.1
content-type: application/json

{
"firstName": "Alexandra",
"lastName": "Wheeler",
"email": "Alex.Wheeler@test.com",
"favoriteColor": "Purple",
"birthday": "03/11/2008"
}



###

//Lesson 3 Start.....................................................................................
POST https://localhost:8080/contacts https/1.1
content-type: application/json

{
"firstName": "Chase",
"lastName": "Wheeler",
"email": "Chase.Wheeler@test.com",
"favoriteColor": "Red",
"birthday": "03/11/2008"
}
###
GET https://localhost:8080/contacts  https/1.1

###

GET https://localhost:8080/contacts https/1.1

###

// Local Host
PUT https://localhost:8080/contacts/63bf79d4c46a1ed00aa450d7 https/1.1
Content-Type: application/json

{
    "firstName": "Chastity",
    "lastName": "Wheeler",
    "email": "Chastity.Wheeler@test.com",
    "favoriteColor": "Mauve",
    "birthday": "03/11/2008"
}

###

DELETE  https://localhost:8080/contacts/63bf79d4c46a1ed00aa450d7 https/1.1

###
// Render Links
GET https://cse341-898f.onrender.com/contacts https/1.1

###

POST  https://cse341-898f.onrender.com/contacts https/1.1
content-type: application/json

{
"firstName": "Harry",
"lastName": "Houdini",
"email": "HarryIamGone@test.com",
"favoriteColor": "Green",
"birthday": "03/24/1874"
}

###

GET https://cse341-898f.onrender.com/contacts https/1.1
###

PUT https://cse341-898f.onrender.com/contacts/63c04a1b1cc10e5714a10158 https/1.1
Content-Type: application/json

{
    "firstName": "Johnny",
    "lastName": "Houdini",
    "email": "JohnnyBGone@test.com",
    "favoriteColor": "Green",
    "birthday": "03/24/1874"
}

###

DELETE  https://cse341-898f.onrender.com/contacts/63c04a1b1cc10e5714a10158 https/1.1